/**
 * this macro is used to check the timestamps generatede by Park and the timestamps generated by Kin
 */

constexpr int MAXHITS = 256;
struct rikenData {
	ULong64_t lupoTimeStamp;
};

struct bdcData {
	ULong64_t TimeStamp;
};

bdcData bdcBuf;
rikenData rikenBuf;

TChain *getRikenChain(const int &runNumber, const std::string &rikenDir);
TChain *getBDCChain(const int &runNum, const std::string &bdcDir);

void checkTimestamps(
	// clang-format off
    const int& runNumber = 1750,
    const std::string &rikenDir="riken",
    const std::string &bdcDir="bdc_3.12"
	// clang-format on
) {

	auto rikenChain = getRikenChain(runNumber, rikenDir);
	auto bdcChain = getBDCChain(runNumber, bdcDir);
	auto entriesBdc = bdcChain->GetEntries();
	auto entriesRiken = rikenChain->GetEntries();

	if (entriesBdc != entriesRiken) {
		std::cerr << " runNumber " << runNumber << " entriesBdc != entriesRiken  " << entriesBdc << " and "
				  << entriesRiken << " respectively." << '\n';
		return;
	}

	for (auto i = 0; i < entriesBdc; i++) {
		bdcChain->GetEntry(i);
		rikenChain->GetEntry(i);

		if (bdcBuf.TimeStamp != rikenBuf.lupoTimeStamp) {
			std::cout << "Mismatch at runNumber " << runNumber << " entry " << i << " bdc: " << bdcBuf.TimeStamp
					  << " riken: " << rikenBuf.lupoTimeStamp << std::endl;
			return;
		}
	}
}

TChain *getRikenChain(const int &runNumber, const std::string &rikenDir) {
	auto chain = new TChain("samurai", "samurai");
	std::string rikenFile = Form("%s/data%d.root", rikenDir.c_str(), runNumber);
	chain->Add(rikenFile.c_str());
	chain->SetBranchAddress("lupoTimeStamp", &rikenBuf.lupoTimeStamp);
	return chain;
}

TChain *getBDCChain(const int &runNum, const std::string &bdcDir) {

	std::string beamData = Form("%s/bdc_%d.root", bdcDir.c_str(), runNum);
	auto chain = new TChain("TBDC");
	chain->Add(beamData.c_str());
	chain->SetBranchAddress("TimeStamp", &bdcBuf.TimeStamp);

	return chain;
}
