/**
 * this macro is used to merge the riken (analyzed to physical observables) and bdc file generated by Park
 * the merge is based on the entry numbers of the two files, which should be the same
 */

constexpr int MAXHITS = 256;
struct rikenData {
	unsigned int runNumber, eventNumber;
	ULong64_t lupoTimeStamp;

	unsigned int kyotoMulti;
	std::array<unsigned int, MAXHITS> kyotoBarId;
	unsigned int vetoMulti;
	std::array<unsigned int, MAXHITS> vetoBarId;
	std::array<double, MAXHITS> vetoTof;
	std::array<double, MAXHITS> vetoTot;
	std::array<double, MAXHITS> vetoTdiff;

	double sbt1_charge;
	int sbt1_time;
	int sbt1_trigger;
	double sbt2_charge;
	int sbt2_time;
	int sbt2_trigger;
	std::array<int, 32> scalerB2f;
};

struct bdcData {
	Double_t tbdc_x;
	Double_t tbdc_y;
	Double_t tbdc_a;
	Double_t tbdc_b;
};

struct mergedData {
	bdcData bdc;
	rikenData riken;
};

bdcData bdcBuf;
rikenData rikenBuf;
mergedData mergedBuf;

TChain *getRikenChain(const int &runNumber, const std::string &rikenDir);
TChain *getBDCChain(const int &runNum, const std::string &bdcDir);
void createMergedBranches(TTree *tree, mergedData &buf);

void mergeRikenBdc(
	// clang-format off
    const int& runNumber = 1266,
    const std::string &bdcDir="bdc_3.12",
    const std::string &rikenDir="riken",
    const std::string &outName = "merged.root"
	// clang-format on
) {

	auto rikenChain = getRikenChain(runNumber, rikenDir);
	auto bdcChain = getBDCChain(runNumber, bdcDir);

	auto entriesBdc = bdcChain->GetEntries();
	auto entriesRiken = rikenChain->GetEntries();

	if (entriesBdc != entriesRiken) {
		std::cerr << "The number of entries in the two files are not the same" << std::endl;
		std::cerr << "run: " << runNumber << " BDC: " << entriesBdc << " Riken: " << entriesRiken << std::endl;
		return;
	}

	auto mergedFile = new TFile(outName.c_str(), "RECREATE");
	auto mergedTree = new TTree("riken", "riken");
	createMergedBranches(mergedTree, mergedBuf);

	for (auto i = 0; i < entriesBdc; i++) {
		bdcChain->GetEntry(i);
		rikenChain->GetEntry(i);
		mergedBuf.bdc = bdcBuf;
		mergedBuf.riken = rikenBuf;
		mergedTree->Fill();
	}

	mergedFile->cd();
	mergedTree->Write();
	mergedFile->Close();
}

TChain *getRikenChain(const int &runNumber, const std::string &rikenDir) {
	auto chain = new TChain("samurai", "samurai");
	std::string rikenFile = Form("%s/data%d.root", rikenDir.c_str(), runNumber);
	chain->Add(rikenFile.c_str());

	chain->SetBranchAddress("runNumber", &rikenBuf.runNumber);
	chain->SetBranchAddress("eventNumber", &rikenBuf.eventNumber);
	chain->SetBranchAddress("lupoTimeStamp", &rikenBuf.lupoTimeStamp);

	chain->SetBranchAddress("kyotoMulti", &rikenBuf.kyotoMulti);
	chain->SetBranchAddress("kyotoBarId", &rikenBuf.kyotoBarId[0]);
	chain->SetBranchAddress("vetoMulti", &rikenBuf.vetoMulti);
	chain->SetBranchAddress("vetoBarId", &rikenBuf.vetoBarId[0]);
	chain->SetBranchAddress("vetoTof", &rikenBuf.vetoTof[0]);
	chain->SetBranchAddress("vetoTot", &rikenBuf.vetoTot[0]);
	chain->SetBranchAddress("vetoTdiff", &rikenBuf.vetoTdiff[0]);

	chain->SetBranchAddress("sbtCharge1", &rikenBuf.sbt1_charge);
	chain->SetBranchAddress("sbtTime1", &rikenBuf.sbt1_time);
	chain->SetBranchAddress("sbtTrigger1", &rikenBuf.sbt1_trigger);
	chain->SetBranchAddress("sbtCharge2", &rikenBuf.sbt2_charge);
	chain->SetBranchAddress("sbtTime2", &rikenBuf.sbt2_time);
	chain->SetBranchAddress("sbtTrigger2", &rikenBuf.sbt2_trigger);
	chain->SetBranchAddress("scalerB2f", &rikenBuf.scalerB2f[0]);

	return chain;
}

TChain *getBDCChain(const int &runNum, const std::string &bdcDir) {

	std::string beamData = Form("%s/bdc_%d.root", bdcDir.c_str(), runNum);
	auto chain = new TChain("TBDC");
	chain->Add(beamData.c_str());

	chain->SetBranchAddress("target_x", &bdcBuf.tbdc_x);
	chain->SetBranchAddress("target_y", &bdcBuf.tbdc_y);
	chain->SetBranchAddress("target_a", &bdcBuf.tbdc_a);
	chain->SetBranchAddress("target_b", &bdcBuf.tbdc_b);

	return chain;
}
void createMergedBranches(TTree *tree, mergedData &buf) {

	tree->Branch("runNumber", &buf.riken.runNumber, "runNumber/i");
	tree->Branch("eventNumber", &buf.riken.eventNumber, "eventNumber/i");
	tree->Branch("lupoTimeStamp", &buf.riken.lupoTimeStamp, "lupoTimeStamp/l");

	tree->Branch("kyotoMulti", &buf.riken.kyotoMulti, "kyotoMulti/i");
	tree->Branch("kyotoBarId", &buf.riken.kyotoBarId[0], "kyotoBarId[kyotoMulti]/i");

	tree->Branch("vetoMulti", &buf.riken.vetoMulti, "vetoMulti/i");
	tree->Branch("vetoBarId", &buf.riken.vetoBarId[0], "vetoBarId[vetoMulti]/i");
	tree->Branch("vetoTof", &buf.riken.vetoTof[0], "vetoTof[vetoMulti]/D");
	tree->Branch("vetoTot", &buf.riken.vetoTot[0], "vetoTot[vetoMulti]/D");
	tree->Branch("vetoTdiff", &buf.riken.vetoTdiff[0], "vetoTdiff[vetoMulti]/D");

	tree->Branch("sbtCharge1", &buf.riken.sbt1_charge, "sbtCharge1/D");
	tree->Branch("sbtTime1", &buf.riken.sbt1_time, "sbtTime1/I");
	tree->Branch("sbtTrigger1", &buf.riken.sbt1_trigger, "sbtTrigger1/I");
	tree->Branch("sbtCharge2", &buf.riken.sbt2_charge, "sbtCharge2/D");
	tree->Branch("sbtTime2", &buf.riken.sbt2_time, "sbtTime2/I");
	tree->Branch("sbtTrigger2", &buf.riken.sbt2_trigger, "sbtTrigger2/I");
	tree->Branch("scalerB2f", &buf.riken.scalerB2f[0], "scalerB2f[32]/I");

	tree->Branch("bdc_x", &bdcBuf.tbdc_x, "bdc_x/D");
	tree->Branch("bdc_y", &bdcBuf.tbdc_y, "bdc_y/D");
	tree->Branch("bdc_a", &bdcBuf.tbdc_a, "bdc_a/D");
	tree->Branch("bdc_b", &bdcBuf.tbdc_b, "bdc_b/D");

	return;
}
